version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch

    steps:
      - checkout

      - run:
          name: "Install dependencies"
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install cookiecutter
      - run:
          name: "Create Starter Project - Snowflake"
          command: |
            . venv/bin/activate
            cookiecutter --no-input gh:fishtown-analytics/dbt-init --checkout ${CIRCLE_BRANCH} name=jaffle_shop project_name=jaffle_shop_snowflake warehouse=snowflake
      - run:
          name: "Create Starter Project - Redshift"
          command: |
            . venv/bin/activate
            cookiecutter --no-input gh:fishtown-analytics/dbt-init --checkout ${CIRCLE_BRANCH} name=jaffle_shop project_name=jaffle_shop_redshift warehouse=redshift
      - run:
          name: "Create Starter Project - BigQuery"
          command: |
            . venv/bin/activate
            cookiecutter --no-input gh:fishtown-analytics/dbt-init --checkout ${CIRCLE_BRANCH} name=jaffle_shop project_name=jaffle_shop_bigquery warehouse=bigquery
      - run:
          name: "Create Starter Project - Postgres"
          command: |
            . venv/bin/activate
            cookiecutter --no-input gh:fishtown-analytics/dbt-init --checkout ${CIRCLE_BRANCH} name=jaffle_shop project_name=jaffle_shop_postgres warehouse=postgres
      - save_cache:
          key: deps1-{{ .Branch }}
          paths:
            - "venv"
